### PR TITLE
update e2e details

### PR DESCRIPTION
**Pull request by wenting-guo**
update e2e details

**What type of PR is this?**

**What this PR does / why we need it**:
update the test case document
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by ErikJiang — APPROVED** [review]

**Comment by YunShiHang** [comment]
good

**Review by YunShiHang — COMMENTED** [review]
/lgtm

**Review by YunShiHang — APPROVED** [review]
/lgtm

**Review by YunShiHang — CHANGES_REQUESTED** [review]
/lgtm

**Review by YunShiHang — APPROVED** [review]

**Review by YunShiHang — COMMENTED** [review]
/lgtm

**Review by YunShiHang — COMMENTED** [review]
/lgtm

**Review by YunShiHang — COMMENTED** [review]
good

**Pull request merged**
