### PR TITLE
Precheck Result Configmap

### PR DESCRIPTION
**Pull request by hangscer8**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

* releated https://github.com/kubean-io/kubean/pull/559 

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by hangscer8** [comment]
result:

```
➜  ~ kubectl get clusters.kubean.io cluster1-demo -o yaml
apiVersion: kubean.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kubean.io/v1alpha1","kind":"Cluster","metadata":{"annotations":{},"labels":{"clusterName":"cluster1-demo"},"name":"cluster1-demo"},"spec":{"hostsConfRef":{"name":"cluster1-demo-hosts-conf","namespace":"kubean-system"},"varsConfRef":{"name":"cluster1-demo-vars-conf","namespace":"kubean-system"}}}
  creationTimestamp: "2023-03-24T02:22:28Z"
  generation: 2
  labels:
    clusterName: cluster1-demo
  name: cluster1-demo
  resourceVersion: "465052"
  uid: 743fffe1-8987-418a-afdf-33bc16ed6640
spec:
  hostsConfRef:
    name: cluster1-demo-hosts-conf
    namespace: kubean-system
  preCheckRef:
    name: cluster1-demo-precheck-result
    namespace: kubean-system
  varsConfRef:
    name: cluster1-demo-vars-conf
    namespace: kubean-system
status:
  conditions:
  - clusterOps: cluster1-demo-ops-1
    startTime: "2023-03-24T02:22:29Z"
    status: Running
➜  ~
➜  ~ kubectl get clusters.kubean.io cluster1-demo -o yaml
➜  ~ kubectl get cm -n kubean-system cluster1-demo-precheck-result -o yaml
apiVersion: v1
data:
  kubean_data_temp_cache: |
    node1:
      ping_connection: "True"
      os_type:
        NAME: CentOS Linux
        VERSION: 7 (Core)
        ID: centos
        ID_LIKE: rhel fedora
        VERSION_ID: "7"
        PRETTY_NAME: CentOS Linux 7 (Core)
        ANSI_COLOR: 0;31
        CPE_NAME: cpe:/o:centos:centos:7
        HOME_URL: https://www.centos.org/
        BUG_REPORT_URL: https://bugs.centos.org/
        CENTOS_MANTISBT_PROJECT: CentOS-7
        CENTOS_MANTISBT_PROJECT_VERSION: "7"
        REDHAT_SUPPORT_PRODUCT: centos
        REDHAT_SUPPORT_PRODUCT_VERSION: "7"
      existing_k8s_service: "True"
kind: ConfigMap
metadata:
  creationTimestamp: "2023-03-24T03:00:36Z"
  name: cluster1-demo-precheck-result
  namespace: kubean-system
  resourceVersion: "471463"
  uid: 63556090-b418-45b1-9912-4dc9abdc74d7
➜  ~
```

**Comment by calvin0327** [comment]
good job

**Comment by hangscer8** [comment]
cmd:
```
ansible-playbook -i /conf/hosts.yml -b --become-user root -e "@/conf/group_vars.yml" /kubespray/precheck.yml
```

**Pull request merged**
