### PR TITLE
load kubeconfig filepath when load rest config fail

### PR DESCRIPTION
**Pull request by HeavenTonight**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
fix(kubean-admission):load kubeconfig filepath when load rest config fail

#### Which issue(s) this PR fixes:
None

### CODE REVIEW

**Comment by ErikJiang** [comment]
What is the purpose of this modification? 
How can we obtain the kubeconfig file within the container image?

**Comment by HeavenTonight** [comment]
> What is the purpose of this modification? How can we obtain the kubeconfig file within the container image?

And then 
> How can we obtain the kubeconfig file within the container image?

I don't know why we use it this way, like this code:
https://github.com/kubean-io/kubean/blob/cb4c77f610dadf17a5d75dbb53d6e3caf4022f24/cmd/kubean-admission/app/app.go#L59
https://github.com/kubean-io/kubean/blob/cb4c77f610dadf17a5d75dbb53d6e3caf4022f24/cmd/kubean-operator/app/app.go#L106

**Comment by HeavenTonight** [comment]
Please review again, thanks! @ErikJiang

**Comment by ErikJiang** [comment]
Please troubleshoot the CI problem：
https://github.com/kubean-io/kubean/actions/runs/8642679500/job/23696047971?pr=1201

**Review by ErikJiang — APPROVED** [review]

**Pull request merged**
